#!/bin/bash
#---------------------------------------------------------------
# Fusion Microservice Kubernetes Utils
# Araf Karsh Hamid, (c) Copyright 2025
# License: Apache 2.0
# Version 0.01
#---------------------------------------------------------------

source ../utils/colimaStatus

echo "---------------------------------------------------------------"
echo "UnInstall the Fusion Water Service in Kubernetes cluster"
echo "---------------------------------------------------------------"

# Ask the user the question
read -p "Do you want to uninstall Fusion-Water-Alpha Service? (yes/y or no/n): " response

# Normalize the input to lowercase for easy comparison
response=$(echo "$response" | tr '[:upper:]' '[:lower:]')

# Process the response
if [[ "$response" == "y" || "$response" == "yes" ]]; then
  echo "1. UnInstall Order Service"
  orderUnInstall
  echo "2. UnInstall Cart Service"
  cartUnInstall
  echo "3. UnInstall Product Service"
  productUnInstall
  echo "4. UnInstall Alpha Service"
  alphaUnInstall
  echo "5. UnInstall the Namespace and Ingress"
  fusionUnInstall
  echo "---------------------------------------------------------------"
elif [[ "$response" == "n" || "$response" == "no" ]]; then
  echo "Alpha Service Uninstallation canceled. Exiting."
else
  echo "Invalid input. Please enter yes/y or no/n."
fi

