#!/bin/bash
#---------------------------------------------------------------
# Fusion Microservice Kubernetes Utils
# Araf Karsh Hamid, (c) Copyright 2025
# License: Apache 2.0
# Version 0.01
#---------------------------------------------------------------

source ../utils/colimaStatus

echo "---------------------------------------------------------------"
echo "UnInstall the Fusion Water Service in Kubernetes cluster"
echo "---------------------------------------------------------------"
echo "1. UnInstall Order Service"
orderUnInstall
echo "2. UnInstall Cart Service"
cartUnInstall
echo "3. UnInstall Product Service"
productUnInstall
echo "4. UnInstall Alpha Service"
alphaUnInstall
echo "5. UnInstall the Namespace and Ingress"
fusionUnInstall
echo "---------------------------------------------------------------"
