#!/bin/bash
#---------------------------------------------------------------
# Fusion Microservice Kubernetes Utils
# Araf Karsh Hamid, (c) Copyright 2025
# License: Apache 2.0
# Version 0.01
#---------------------------------------------------------------

source ../utils/colimaStatus

echo "---------------------------------------------------------------"
echo "Install the Fusion Cart Service in Kubernetes cluster"
echo "---------------------------------------------------------------"
echo "1. Deploy the Pods/Services/Ingress in Kubernetes cluster"
kubectl create -f ../Yamls/fusion-07-water-cart-service.yaml
kubectl create -f ../Yamls/fusion-08-water-cart-deploy.yaml
kubectl create -f ../Yamls/fusion-13-water-cart-hpa.yaml
echo "---------------------------------------------------------------"
