#!/bin/bash
#---------------------------------------------------------------
# Fusion Microservice Kubernetes Utils
# Araf Karsh Hamid, (c) Copyright 2025
# License: Apache 2.0
# Version 0.01
#---------------------------------------------------------------

source ../utils/colimaStatus

echo "---------------------------------------------------------------"
echo "kubectl delete virtualservice fusion-*-vs -n fusion"
kubectl delete virtualservice fusion-alpha-vs -n fusion
kubectl delete virtualservice fusion-product-vs -n fusion
kubectl delete virtualservice fusion-cart-vs -n fusion
kubectl delete virtualservice fusion-order-vs -n fusion
echo "---------------------------------------------------------------"
