#!/bin/bash
#---------------------------------------------------------------
# Fusion Microservice Kubernetes Utils
# Araf Karsh Hamid, (c) Copyright 2025
# License: Apache 2.0
# Version 0.01
#---------------------------------------------------------------

source ../utils/colimaStatus

echo "---------------------------------------------------------------"
echo "Install the Fusion Water Services in Kubernetes cluster"
echo "---------------------------------------------------------------"
echo "1. Setup the Namespace / Gateway "
istioFusionInstall
echo "2. Setup VirtualServices"
istioApplyVirtualService
echo "3. Setup Alpha Service"
alphaInstall
echo "4. Setup Product Service"
productInstall
echo "5. Setup Cart Service"
cartInstall
echo "6. Setup Order Service"
orderInstall
echo "---------------------------------------------------------------"
