#!/bin/bash
echo "helm install istio-ingress istio/gateway -n istio-ingress -f istio-gateway-values-80.yaml --wait --timeout 10m"
helm install istio-ingress istio/gateway -n istio-ingress -f istio-gateway-values-80.yaml --wait --timeout 10m
#helm install istio-ingress istio/gateway -n istio-ingress -f istio-gateway-values.yaml --wait --timeout 10m
