#!/bin/bash
#---------------------------------------------------------------
# Fusion Microservice Kubernetes Utils
# Araf Karsh Hamid, (c) Copyright 2025
# License: Apache 2.0
# Version 0.01
#---------------------------------------------------------------

source ../../utils/colimaStatus

# uninstall NGINX Gateway if found
uninstall_if_nginx_gateway_found

# uninstall NGINX ingress if found
uninstall_if_nginx_ingress_found

# Install Istio ingress if not found
install_if_istio_ingress_missing

echo "---------------------------------------------------------------"
echo "Install the Fusion Water Services in Kubernetes Istio cluster"
echo "---------------------------------------------------------------"
echo "1. Setup the Istio Namespace / Gateway "
istioFusionInstall
echo "2. Setup Istio VirtualServices"
istioApplyVirtualService
cd ../app
allInstall
cd ../svc-mesh
echo "---------------------------------------------------------------"
echo "Sleeping for 7 seconds..."
sleep 7
echo "---------------------------------------------------------------"
list
