#!/bin/bash
#---------------------------------------------------------------
# Fusion Microservice Kubernetes Utils
# Araf Karsh Hamid, (c) Copyright 2025
# License: Apache 2.0
# Version 0.01
#---------------------------------------------------------------

source ../../utils/colimaStatus

echo "---------------------------------------------------------------"
echo "Upgrade the Fusion Water Services in Kubernetes Istio cluster"
cd ../app
allUpgrade
cd ../svc-mesh
echo "---------------------------------------------------------------"
list
