#!/bin/bash
#---------------------------------------------------------------
# Fusion Microservice Kubernetes Utils
# Araf Karsh Hamid, (c) Copyright 2025
# License: Apache 2.0
# Version 0.01
#---------------------------------------------------------------

source ../../utils/colimaStatus

echo "---------------------------------------------------------------"
echo "kubectl delete deploy water-*-deploy -n fusion"
kubectl delete hpa water-product-hpa -n fusion
kubectl delete hpa water-cart-hpa -n fusion
kubectl delete hpa water-order-hpa -n fusion
echo "---------------------------------------------------------------"
kubectl delete deploy water-product-deploy -n fusion
kubectl delete deploy water-cart-deploy -n fusion
kubectl delete deploy water-order-deploy -n fusion
echo "---------------------------------------------------------------"
