#!/bin/bash
#---------------------------------------------------------------
# Fusion Microservice Kubernetes Utils
# Araf Karsh Hamid, (c) Copyright 2025
# License: Apache 2.0
# Version 0.01
#---------------------------------------------------------------

source ../../utils/colimaStatus

echo "---------------------------------------------------------------"
echo "Install the Fusion Service in Kubernetes/Istio cluster"
echo "---------------------------------------------------------------"
echo "1. Deploy the Istio Namespace / Gateway in Kubernetes cluster"
kubectl create -f ../../Yamls/svc-mesh/fusion-31-istio-namespace.yaml
kubectl create -f ../../Yamls/svc-mesh/fusion-32-istio-gateway.yaml
echo "---------------------------------------------------------------"
