#!/bin/bash
#---------------------------------------------------------------
# Fusion Kubernetes Utils
# Araf Karsh Hamid, (c) Copyright 2025
# License: Apache 2.0
# Version 0.01
#---------------------------------------------------------------

source ../../utils/colimaStatus

echo "---------------------------------------------------------------"
echo "Alpha App Configuration and Secrets"
echo "---------------------------------------------------------------"
kubectl get secrets,configmaps -o wide -n fusion
echo "---------------------------------------------------------------"
echo "Pods / Deployments / Services / Endpoints"
echo "---------------------------------------------------------------"
kubectl get pods,deploy,svc,ep -o wide -n fusion
echo "---------------------------------------------------------------"
echo "Ingress : Istio Gateway / Virtual Service / Destination Rule"
echo "---------------------------------------------------------------"
kubectl get gw,vs,dr -o wide -n fusion
echo "---------------------------------------------------------------"
echo "List All Pods of Istio Ingress "
echo "---------------------------------------------------------------"
kubectl get svc -n istio-ingress
echo "---------------------------------------------------------------"
kubectl get hpa -o wide -n fusion
echo "---------------------------------------------------------------"
