#!/bin/bash
#---------------------------------------------------------------
# Fusion Kubernetes Utils
# Araf Karsh Hamid, (c) Copyright 2025
# License: Apache 2.0
# Version 0.01
#---------------------------------------------------------------

cd ../../
rolloutStatus
