#!/bin/bash
#---------------------------------------------------------------
# Base OS Installation
# Araf Karsh Hamid, (c) Copyright 2025
# License: Apache 2.0
# Version 0.01
#---------------------------------------------------------------
# Scan Container for Vulnerabilities
# --------------------------------------------------------------

# Source the organization-wide config
source ../utils/config-org.env
source utils/common-functions
source ../utils/colimaStatus

# Call the validation function with "$@"
validate_params "$@"

determine_os "$1"

echo "Scanning $ORG/$SERVICE for vulnerabilities"
docker scan $ORG/$SERVICE
