#!/bin/bash
#---------------------------------------------------------------
# Base OS Installation
# Araf Karsh Hamid, (c) Copyright 2025
# License: Apache 2.0
# Version 0.01
#---------------------------------------------------------------
# Start Container
#---------------------------------------------------------------

# Source the organization-wide config
source ../utils/config-org.env
source utils/common-functions
source ../utils/colimaStatus

# Call the validation function with "$@"
validate_params "$@"

determine_os "$1"

PORT=9090
API=$3

echo "docker container run --name $ORG-$SERVICE -d --rm -p $PORT:9090 $ORG/$SERVICE"
docker container run --name $ORG-$SERVICE -d --rm -p $PORT:9090 $ORG/$SERVICE
echo "Checkout API: http://localhost:$PORT/api/v1/$API/swagger-ui.html"
echo "Container id for $SERVICE ="`docker container ls | grep $SERVICE | tr -s " " | cut -d " " -f 1`
docker container ls | grep $SERVICE | tr -s " " | cut -d " " -f 1 > $SERVICE.cid
