#!/bin/bash
#---------------------------------------------------------------
# Base OS Installation
# Araf Karsh Hamid, (c) Copyright 2025
# License: Apache 2.0
# Version 0.01
#---------------------------------------------------------------
# Stop Container
#---------------------------------------------------------------

# Source the organization-wide config
source ../utils/config-org.env
source utils/common-functions
source ../utils/colimaStatus

# Call the validation function with "$@"
validate_params "$@"

determine_os "$1"

echo "docker container stop $ORG-$SERVICE"
docker container stop $ORG-$SERVICE
docker rm $ORG-$SERVICE
mv $SERVICE.cid $SERVICE.cid.old
