#!/bin/bash
#---------------------------------------------------------------
# Sigma Alpine Installation
# Araf Karsh Hamid, (c) Copyright 2025
#
# Version 0.01
#---------------------------------------------------------------
# Pull Sigma Container
#---------------------------------------------------------------
echo "docker pull arafkarsh/sigma"
docker pull arafkarsh/sigma
