#!/bin/bash
#---------------------------------------------------------------
# Sigma Alpine Installation
# Araf Karsh Hamid, (c) Copyright 2025
#
# Version 0.01
#---------------------------------------------------------------
# Stop Sigma Container
#---------------------------------------------------------------
echo "docker container stop sigma"
docker container stop sigma
