#!/bin/bash
#---------------------------------------------------------------
# Kappa Alpine Installation
# Araf Karsh Hamid, (c) Copyright 2025
#
# Version 0.01
#---------------------------------------------------------------
# Pull Kappa Container
#---------------------------------------------------------------
echo "docker pull arafkarsh/kappa"
docker pull arafkarsh/kappa
