#!/bin/bash
#---------------------------------------------------------------
# Kappa Alpine Installation
# Araf Karsh Hamid, (c) Copyright 2025
#
# Version 0.01
#---------------------------------------------------------------
# Stop Kappa Container
#---------------------------------------------------------------
echo "docker container stop kappa"
docker container stop kappa
