#!/bin/bash
#---------------------------------------------------------------
# Lambda Alpine Installation
# Araf Karsh Hamid, (c) Copyright 2025
#
# Version 0.01
#---------------------------------------------------------------
# Pull Lambda Container
#---------------------------------------------------------------
echo "docker pull arafkarsh/lambda"
docker pull arafkarsh/lambda
