#!/bin/bash
#---------------------------------------------------------------
# Lambda Alpine Installation
# Araf Karsh Hamid, (c) Copyright 2025
#
# Version 0.01
#---------------------------------------------------------------
# Restart Lambda Container
#---------------------------------------------------------------
echo "docker container stop lambda"
docker container stop lambda
echo "docker container run --name lambda -d --rm -p 84:84 arafkarsh/lambda"
docker container run --name lambda -d --rm -p 84:84 arafkarsh/lambda
