#!/bin/bash
#---------------------------------------------------------------
# Lambda Alpine Installation
# Araf Karsh Hamid, (c) Copyright 2025
#
# Version 0.01
#---------------------------------------------------------------
# Stop Lambda Container
#---------------------------------------------------------------
echo "docker container stop lambda"
docker container stop lambda
