#---------------------------------------------------------------
# Java Alpine Installation
# Araf Karsh Hamid, (c) Copyright 2025
#
# Version 0.01
#---------------------------------------------------------------
# Java 11 Container
#---------------------------------------------------------------

FROM arafkarsh/alpine:3.21

# Metadata
LABEL maintainer="Araf Karsh Hamid <araf.karsh@gmail.com>" \
      description="This Dockerfile creates the Java Alpine image." \
      version="1.0" \
      org.opencontainers.image.authors="Araf Karsh Hamid <araf.karsh@gmail.com>" \
      org.opencontainers.image.version="1.0" \
      org.opencontainers.image.licenses="Apache 2"

RUN  apk update \
  && apk upgrade \
  && apk add --update openjdk11 tzdata \
  && rm -rf /var/cache/apk/*

# Add profile information to .bash_profile
RUN { \
    echo "echo \"----------------------------------------------------------------\""; \
    echo "java -version"; \
    echo "echo \"----------------------------------------------------------------\""; \
    echo "echo \"Alpine arm64/amd64 Java 11 Container\""; \
    echo "echo \"----------------------------------------------------------------\""; \
  } >> /home/ozazo/.bash_profile

# Enable User ozazo at this Level
USER ozazo

ENTRYPOINT ["/bin/bash", "--login"]
