#!/bin/bash
#---------------------------------------------------------------
# Fusion Microservice Kubernetes Utils
# Araf Karsh Hamid, (c) Copyright 2025
# License: Apache 2.0
# Version 0.01
#---------------------------------------------------------------

source utils/colimaStatus

podName=$(kubectl get pods -n istio-ingress | grep "istio-ingress" | awk 'NR==1 {print $1}')

echo "---------------------------------------------------------------"
echo "kubectl get pods -o wide -n kube-system"
kubectl get pods -o wide -n kube-system
echo "---------------------------------------------------------------"
echo "kubectl get pods -o wide -n istio-ingress"
kubectl get pods -o wide -n istio-ingress
kubectl get svc -o wide -n istio-ingress
echo "---------------------------------------------------------------"
echo "Check the Logs of the Pod=$podName -n istio-ingress"
echo "---------------------------------------------------------------"
echo "istioctl proxy-config routes -n istio-ingress $podName"
istioctl proxy-config routes -n istio-ingress $podName
