#!/bin/bash
#---------------------------------------------------------------
# Fusion Microservice Kubernetes Utils
# Araf Karsh Hamid, (c) Copyright 2025
# License: Apache 2.0
# Version 0.01
#---------------------------------------------------------------

source utils/colimaStatus

podName=`kubectl get pods | awk 'NR>1 {print $1}'`

echo "Check the Logs of the Pod=$podName -n fusion"
kubectl logs -f $podName -n fusion
