#!/bin/bash
#---------------------------------------------------------------
# Fusion Microservice Kubernetes Utils
# Araf Karsh Hamid, (c) Copyright 2025
# License: Apache 2.0
# Version 0.01
#---------------------------------------------------------------

source utils/colimaStatus

echo "kubectl run debug-pod --rm --image=arafkarsh/podshell:1 -it -n fusion"
kubectl run debug-pod --rm --image=arafkarsh/podshell:1 -it -n fusion
