#!/bin/bash
#---------------------------------------------------------------
# Fusion Kubernetes Utils
# Araf Karsh Hamid, (c) Copyright 2025
# License: Apache 2.0
# Version 0.01
#---------------------------------------------------------------

source utils/colimaStatus

echo "---------------------------------------------------------------"
echo "List All Pods of Kube System "
kubectl get pods,svc -o wide -n kube-system
echo "---------------------------------------------------------------"
echo "List All Pods of Kube base "
kubectl get pods,svc -o wide -n kube-base
echo "---------------------------------------------------------------"
echo "List All Pods of nginx System "
kubectl get pods,svc -o wide -n ingress-nginx
echo "---------------------------------------------------------------"
echo "List All Pods of Istio Ingress "
kubectl get pods,svc -o wide -n istio-ingress
kubectl get pods,svc -o wide -n istio-system
echo "---------------------------------------------------------------"
