#!/bin/bash
#---------------------------------------------------------------
# Fusion Kubernetes Utils
# Araf Karsh Hamid, (c) Copyright 2025
# License: Apache 2.0
# Version 0.01
#---------------------------------------------------------------

source utils/colimaStatus

# Check if required arguments are provided
if [ -z "$1" ] || [ -z "$2" ]; then
    echo "---------------------------------------------------------------"
    echo "Usage: $0 <deployment_name> <revision_number>"
    echo "---------------------------------------------------------------"
    kubectl rollout history deployment $1 -n fusion
    echo "---------------------------------------------------------------"
    kubectl get deploy -o wide -n fusion
    echo "---------------------------------------------------------------"
    exit 1

fi

echo "---------------------------------------------------------------"
echo "Rollback History"
echo "---------------------------------------------------------------"
kubectl rollout history deployment $1 -n fusion
echo "---------------------------------------------------------------"
echo "Rollback Deployment $1 to Revision=$2"
echo "---------------------------------------------------------------"
kubectl rollout undo deployment $1 --to-revision=$2 -n fusion
kubectl rollout status deployment $1 -n fusion
echo "---------------------------------------------------------------"
echo "Pods / Deployments / Services / Endpoints"
echo "---------------------------------------------------------------"
kubectl get pods,deploy,svc,ep -o wide -n fusion
echo "---------------------------------------------------------------"
