#!/bin/bash
#---------------------------------------------------------------
# Fusion Kubernetes Utils
# Araf Karsh Hamid, (c) Copyright 2025
# License: Apache 2.0
# Version 0.01
#---------------------------------------------------------------

source utils/colimaStatus

podName=`kubectl get pods | awk 'NR>1 {print $1}'`

echo "Log into the Pod Shell..."
kubectl exec -it $podName -- sh
