#!/bin/bash
#---------------------------------------------------------------
# Fusion Kubernetes Utils
# Araf Karsh Hamid, (c) Copyright 2025
# License: Apache 2.0
# Version 0.01
#---------------------------------------------------------------

source utils/colimaStatus

echo "---------------------------------------------------------------"
echo "Verify the Colima + Kubernetes Setup by Testing - Alpha Service"
echo "---------------------------------------------------------------"
echo "curl http://localhost/$1"
curl http://localhost/$1
