#! /bin/bash
#---------------------------------------------------------------
# Base OS Installation
# Araf Karsh Hamid, (c) Copyright 2025
# License: Apache 2.0
# Version 0.01
#---------------------------------------------------------------
# Build the Latest Alpine Container
#---------------------------------------------------------------

# Source the organization-wide config
source ../utils/config-org.env
source ../utils/colimaStatus

echo "docker buildx build --platform linux/arm64,linux/amd64 --rm=true -t $ORG/oshell --push ."
docker buildx build --platform linux/arm64,linux/amd64 --rm=true -t $ORG/oshell --push .
