#!/bin/bash
#---------------------------------------------------------------
# OShell Installation
# Araf Karsh Hamid, (c) Copyright 2025
# License: Apache 2.0
# Version 0.01
#---------------------------------------------------------------
# Build the OShell Container
#---------------------------------------------------------------

# Source the organization-wide config
source ../utils/config-org.env
source ../utils/colimaStatus


echo "docker build --rm=true -t $ORG/oshell ."
docker build --rm=true -t $ORG/oshell .
