#!/bin/bash
#---------------------------------------------------------------
# Fusion Microservice Kubernetes Utils
# Araf Karsh Hamid, (c) Copyright 2025
# License: Apache 2.0
# Version 0.01
#---------------------------------------------------------------

source ../../utils/colimaStatus

echo "---------------------------------------------------------------"
echo "Install the Alpha Services (Alpha, Product, Cart, Order).....  "
echo "---------------------------------------------------------------"
echo "1. Setup Alpha Service"
alphaInstall
echo "2. Setup Product Service"
productInstall
echo "3. Setup Cart Service"
cartInstall
echo "4. Setup Order Service"
orderInstall
