#!/bin/bash
#---------------------------------------------------------------
# Fusion Microservice Kubernetes Utils
# Araf Karsh Hamid, (c) Copyright 2025
# License: Apache 2.0
# Version 0.01
#---------------------------------------------------------------

source ../../utils/colimaStatus

echo "---------------------------------------------------------------"
echo "A/B Testing the Alpha Services to v1/v2 (Product, Cart, Order).."
echo "---------------------------------------------------------------"
echo "1. Upgrade (A/B Testing) Product Service"
productUpgradeABTesting
echo "2. Upgrade (A/B Testing) Cart Service"
cartUpgradeABTesting
echo "3. Upgrade (A/B Testing) Order Service"
orderUpgradeABTesting
echo "---------------------------------------------------------------"
echo "Rollout Status... "
echo "---------------------------------------------------------------"
kubectl rollout status deployment water-product-deploy-v2 -n fusion
kubectl rollout status deployment water-cart-deploy-v2 -n fusion
kubectl rollout status deployment water-order-deploy-v2 -n fusion
 
