#!/bin/bash
#---------------------------------------------------------------
# Fusion Microservice Kubernetes Utils
# Araf Karsh Hamid, (c) Copyright 2025
# License: Apache 2.0
# Version 0.01
#---------------------------------------------------------------

source ../../utils/colimaStatus

echo "---------------------------------------------------------------"
echo "Canary Upgrade: Alpha Services to v2.0.0 (Product, Cart, Order)"
echo "---------------------------------------------------------------"
echo "1. Canary Upgrade Product Service"
productUpgradeCanary
echo "2. Canary Upgrade Cart Service"
cartUpgradeCanary
echo "3. Canary Upgrade Order Service"
orderUpgradeCanary
echo "---------------------------------------------------------------"
echo "Rollout Status... "
echo "---------------------------------------------------------------"
kubectl rollout status deployment water-product-deploy -n fusion
kubectl rollout status deployment water-cart-deploy -n fusion
kubectl rollout status deployment water-order-deploy -n fusion
 
