#!/bin/bash
#---------------------------------------------------------------
# Fusion Microservice Kubernetes Utils
# Araf Karsh Hamid, (c) Copyright 2025
# License: Apache 2.0
# Version 0.01
#---------------------------------------------------------------

source ../../utils/colimaStatus

echo "Delete the Fusion Water Alpha Deployment..."
echo "kubectl delete deployment water-alpha-deploy -n fusion"
kubectl delete deployment water-alpha-deploy -n fusion
kubectl get deployment -o wide -n fusion
