#!/bin/bash
#---------------------------------------------------------------
# Fusion Microservice Kubernetes Utils
# Araf Karsh Hamid, (c) Copyright 2025
# License: Apache 2.0
# Version 0.01
#---------------------------------------------------------------

source ../../utils/colimaStatus

echo "Deploy the Fusion Water Cart Service in Kubernetes cluster"
echo "kubectl create --save-config -f ../../Yamls/app/fusion-08-water-cart-deploy.yaml"
kubectl create --save-config -f ../../Yamls/app/fusion-08-water-cart-deploy.yaml
kubectl get deploy -o wide -n fusion
