#!/bin/bash
#---------------------------------------------------------------
# Fusion Microservice Kubernetes Utils
# Araf Karsh Hamid, (c) Copyright 2025
# License: Apache 2.0
# Version 0.01
#---------------------------------------------------------------
# For Both A/B Testing and Blue Green Deployment the product
# upgrades are always Blue Green Deployment.
# What differentiates between them is the Traffic Split. 
# In Blue Green deployment the Traffic is 
# Blue = 100%, Green = 0% OR
# Blue = 0%, Green = 100%
#---------------------------------------------------------------

source ../../utils/colimaStatus

echo "Upgrade (Canary) the Fusion Water Order Service in Kubernetes cluster"
kubectl apply -f ../../Yamls/app/fusion-09-water-order-service-blue.yaml
kubectl create --save-config -f ../../Yamls/app/fusion-09-water-order-service-green.yaml
kubectl create --save-config -f ../../Yamls/app/fusion-10-water-order-deploy-bg.yaml
kubectl create --save-config -f ../../Yamls/app/fusion-14-water-order-hpa-green.yaml
kubectl get deploy -o wide -n fusion
kubectl rollout history deployment water-order-deploy-green -n fusion
kubectl rollout status deployment water-order-deploy-green -n fusion
