#!/bin/bash
#---------------------------------------------------------------
# Fusion Microservice Kubernetes Utils
# Araf Karsh Hamid, (c) Copyright 2025
# License: Apache 2.0
# Version 0.01
#---------------------------------------------------------------

source ../../utils/colimaStatus

echo "---------------------------------------------------------------"
echo "Install the Fusion Product Service in Kubernetes cluster"
echo "---------------------------------------------------------------"
echo "1. Deploy the Pods/Services/Ingress in Kubernetes cluster"
kubectl create -f ../../Yamls/app/fusion-05-water-product-service.yaml
kubectl create -f ../../Yamls/app/fusion-06-water-product-deploy.yaml
kubectl create -f ../../Yamls/app/fusion-12-water-product-hpa.yaml
echo "---------------------------------------------------------------"
