#!/bin/bash
#---------------------------------------------------------------
# Fusion Microservice Kubernetes Utils
# Araf Karsh Hamid, (c) Copyright 2025
# License: Apache 2.0
# Version 0.01
#---------------------------------------------------------------
# For Both A/B Testing and Blue Green Deployment the product
# upgrades are always Blue Green Deployment.
# What differentiates between them is the Traffic Split. 
# In Blue Green deployment the Traffic is 
# Blue = 100%, Green = 0% OR
# Blue = 0%, Green = 100%
#---------------------------------------------------------------

source ../../utils/colimaStatus

echo "Upgrade (Blue/Green) the Fusion Water Product Service in Kubernetes cluster"
kubectl create --save-config -f ../../Yamls/app/fusion-06-water-product-deploy-bg.yaml
kubectl apply -f ../../Yamls/app/fusion-12-water-product-hpa-green.yaml
kubectl get deploy -o wide -n fusion
kubectl rollout history deployment water-product-deploy-green -n fusion
kubectl rollout status deployment water-product-deploy-green -n fusion
