#!/bin/bash
#---------------------------------------------------------------
# Echo Installation
# Araf Karsh Hamid, (c) Copyright 2025
#
# Version 0.01
#---------------------------------------------------------------
# Build the Container
#---------------------------------------------------------------
echo "docker build -t arafkarsh/echo ."
docker build -t arafkarsh/echo .
