#---------------------------------------------------------------
# Echo Installation
# Araf Karsh Hamid, (c) Copyright 2025
#
# Version 0.01
#---------------------------------------------------------------
# 
FROM hashicorp/http-echo:0.2.3

EXPOSE 5678/tcp

ENTRYPOINT ["/http-echo"]
