#!/bin/bash
#---------------------------------------------------------------
# Echo Installation
# Araf Karsh Hamid, (c) Copyright 2025
#
# Version 0.01
#---------------------------------------------------------------
# Run the Container
#---------------------------------------------------------------
echo docker container run -d -p 5678:5678 arafkarsh/echo -text="Hello to the World of Fusion Music!"
docker container run -d -p 5678:5678 arafkarsh/echo -text="Hello to the World of Fusion Music!"
