#!/bin/bash
#---------------------------------------------------------------
# Echo Installation
# Araf Karsh Hamid, (c) Copyright 2025
#
# Version 0.01
#---------------------------------------------------------------
# Test the Container
#---------------------------------------------------------------
echo "Response from Echo Server:`curl localhost:5678`"
