#!/bin/bash

echo "Chapter 1: Create Kubernetes Cluster with Istio"
echo "1.1 Create Multi Node Cluster with 1 Masters, and 3 Worker Nodes"
echo "KinD Version >> "`kind version`
kind create cluster --config setup/delta-cluster-4-nodes.yaml

# Calico
echo "1.2 Install Calico Network Driver"
kubectl create -f https://docs.projectcalico.org/manifests/tigera-operator.yaml
kubectl apply -f setup/calico.yaml

sleep 10
kubectl get pods -n calico-system

# Metrics Server
echo "1.3 Install Metrics Server"
kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml

echo "1.4 To Install the Apps run the following command"
echo "$ ch3-sigma-install-apps"
