# Cart Microservice - Deployment / Replicaset / Pod
apiVersion: apps/v1
kind: Deployment
metadata:
  name: water-cart-deploy-green
  namespace: fusion
  labels:
    app: water-cart-deploy-green
  annotations:
    kubernetes.io/change-cause: "Blue/Green container image to v2.0.0"
spec:
  revisionHistoryLimit: 100  # Ensures Kubernetes retains the last 100 revisions
  replicas: 2
  selector:
    matchLabels:
      # Matching the labels from Pod MetaData, Multiple labels can be used
      app: water-cart-pod
      version: "2.0.0"
  minReadySeconds: 5
  strategy:
    # Re-Create / Rolling Update
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: water-cart-pod
        version: "2.0.0"
        release: stable
        organization: Ozazo
    spec:
      containers:
      - name: water-cart-container
        image: arafkarsh/mock-cart-ui:2.0.0
        # Use Always ONLY for Development purpose.
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 92
        resources:
          # QoS : [Guaranteed], BestEffort, Burstable
          # Pod will not be launched if the Hardware  resources are not available
          limits:
            cpu: 5m
            memory: 16Mi
          requests:
            cpu: 5m
            memory: 16Mi

