# Alpha Microservice -  Deployment / Replicaset / Pod
apiVersion: apps/v1
kind: Deployment
metadata:
  name: water-alpha-deploy
  namespace: fusion
  labels:
    app: water-alpha-deploy
  annotations:
    kubernetes.io/change-cause: "Updated the container image to v1.0.0"
spec:
  revisionHistoryLimit: 100  # Ensures Kubernetes retains the last 100 revisions
  replicas: 2
  selector:
    matchLabels:
      # Matching the labels from Pod MetaData, Multiple labels can be used
      app: water-alpha-pod
  minReadySeconds: 5
  strategy:
    # Re-Create / Rolling Update
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: water-alpha-pod
        version: "1.0.0"
        release: stable
        organization: Ozazo
    spec:
      containers:
      - name: water-alpha-container
        image: arafkarsh/alpha:1.0.0
        # Use Always ONLY for Development purpose.
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 81
        resources:
          # QoS : [Burstable], BestEffort, Guaranteed
          # Pod will not be launched if the Hardware  resources are not available
          limits:
            cpu: 5m
            memory: 16Mi
          requests:
            cpu: 5m
            memory: 12Mi

