#!/bin/bash
#---------------------------------------------------------------
# OShell Installation
# Araf Karsh Hamid, (c) Copyright 2025
# License: Apache 2.0
# Version 0.01
#---------------------------------------------------------------
# OShell Container
#---------------------------------------------------------------

# Source the organization-wide config
source ../utils/config-org.env
source ../utils/colimaStatus

echo "docker container run -it $ORG/oshell"
docker container run -it $ORG/oshell 
