#! /bin/bash
#---------------------------------------------------------------
# Cleanup the Docker images
# Araf Karsh Hamid, (c) Copyright 2025
# License: Apache 2.0
# Version 0.01
#---------------------------------------------------------------
source colimaStatus

echo "Docker Repository List"
docker images

echo
echo "Cleaning up Dangling Images"
echo "docker images -f "dangling=true" -q | xargs docker rmi -f"
docker images -f "dangling=true" -q | xargs docker rmi -f

echo
echo "Docker System Space Before Prune"
docker system df

echo
echo "Docker System Prune"
#docker system prune

echo
echo "Docker System Space After Prune"
docker system df

