#! /bin/bash
#---------------------------------------------------------------
# Server Installation
# Araf Karsh Hamid, (c) Copyright 2025
# License: Apache 2.0
# Version 0.01
#---------------------------------------------------------------
# Build the Server Container 
#---------------------------------------------------------------

# Source the organization-wide config
source ../utils/config-org.env
source utils/common-functions
source ../utils/colimaStatus

# Call the validation function with "$@"
validate_params "$@"

# Set version from $2
set_version "$2"

# Determine configuration based on $1
determine_config "$1"

# Build the Docker Image
echo "docker build --rm=true -t $ORG/$SERVICE -f $DOCKER_FILE ."
docker build --rm=true -t $ORG/$SERVICE -f $DOCKER_FILE . 
