#!/bin/bash
#---------------------------------------------------------------
# Server Installation
# Araf Karsh Hamid, (c) Copyright 2025
# License: Apache 2.0
# Version 0.01
#---------------------------------------------------------------
# List all Docker Images
#---------------------------------------------------------------

source ../utils/colimaStatus

echo "List all the Running Docker Containers"
docker ps
