#!/bin/bash
#---------------------------------------------------------------
# Server Installation
# Araf Karsh Hamid, (c) Copyright 2025
# License: Apache 2.0
# Version 0.01
#---------------------------------------------------------------
# Push Server Docker Container to Docker Hub
#---------------------------------------------------------------

echo "docker container run -it arafkarsh/podshell:1"
docker container run -it arafkarsh/podshell:1
