#!/bin/bash
#---------------------------------------------------------------
# Fusion Microservice Kubernetes Utils
# Araf Karsh Hamid, (c) Copyright 2025
# License: Apache 2.0
# Version 0.01
#---------------------------------------------------------------

source ../../utils/colimaStatus

echo "---------------------------------------------------------------"
echo "Checking the Ingress Drivers... "
echo "---------------------------------------------------------------"
# uninstall NGINX Gateway if found
uninstall_if_nginx_gateway_found

# uninstall Istio ingress if found
uninstall_if_istio_ingress_found

# Install Kubernetes Gateway API CRDs
install_k8s_gw_crds

# Function to check and install NGINX ingress if not found
install_if_nginx_ingress_missing

echo "---------------------------------------------------------------"
echo "Sleeping for 7 seconds to activate the Ingress Controller..."
sleep 7
echo "---------------------------------------------------------------"
echo "Install the Fusion Water Services in Kubernetes cluster"
echo "---------------------------------------------------------------"
echo "Setup the Namespace and Ingress"
k8sFusionInstall
cd ../app
allInstall
cd ../k8s
echo "---------------------------------------------------------------"
echo "Sleeping for 7 seconds..."
sleep 7
echo "---------------------------------------------------------------"
list
