#!/bin/bash
#---------------------------------------------------------------
# Fusion Microservice Kubernetes Utils
# Araf Karsh Hamid, (c) Copyright 2025
# License: Apache 2.0
# Version 0.01
#---------------------------------------------------------------

source ../../utils/colimaStatus

echo "---------------------------------------------------------------"
echo "kubectl apply -f ../../Yamls/fusion-02-water-ingress.yaml"
kubectl apply -f ../../Yamls/fusion-02-water-ingress.yaml
echo "---------------------------------------------------------------"
kubectl describe ingress fusion-water-gw-ingress -n fusion 
echo "---------------------------------------------------------------"
