#!/bin/bash
#---------------------------------------------------------------
# Fusion Kubernetes Utils
# Araf Karsh Hamid, (c) Copyright 2025
# License: Apache 2.0
# Version 0.01
#---------------------------------------------------------------

echo "---------------------------------------------------------------"
echo "App Configuration and Secrets"
echo "---------------------------------------------------------------"
kubectl get configmaps -o wide -n fusion
echo "---------------------------------------------------------------"
kubectl get secrets -o wide -n fusion
echo "---------------------------------------------------------------"
echo "Pods / Deployments / Services"
echo "---------------------------------------------------------------"
kubectl get pods,deploy,svc -o wide -n fusion
echo "---------------------------------------------------------------"
echo "Ingress : K8s / nginx "
echo "---------------------------------------------------------------"
kubectl get ingress -o wide -n fusion
kubectl get service nginx-ingress-ingress-nginx-controller -n ingress-nginx 
echo "---------------------------------------------------------------"
echo "Horizontal Pod AutoScaler"
echo "---------------------------------------------------------------"
kubectl get hpa -o wide -n fusion
echo "---------------------------------------------------------------"
