#!/bin/bash
#---------------------------------------------------------------
# Omega Alpine Installation
# Araf Karsh Hamid, (c) Copyright 2025
#
# Version 0.01
#---------------------------------------------------------------
# Pull Omega Container
#---------------------------------------------------------------
echo "docker pull arafkarsh/omega"
docker pull arafkarsh/omega
