#!/bin/bash
#---------------------------------------------------------------
# Omega Alpine Installation
# Araf Karsh Hamid, (c) Copyright 2025
#
# Version 0.01
#---------------------------------------------------------------
# Restart Omega Container
#---------------------------------------------------------------
echo "docker container stop omega"
docker container stop omega
echo "docker container run --name omega -d --rm -p 82:82 arafkarsh/omega"
docker container run --name omega -d --rm -p 82:82 arafkarsh/omega
