#!/bin/bash
#---------------------------------------------------------------
# Omega Alpine Installation
# Araf Karsh Hamid, (c) Copyright 2025
#
# Version 0.01
#---------------------------------------------------------------
# Stop Omega Container
#---------------------------------------------------------------
echo "docker container stop omega"
docker container stop omega
