#!/bin/bash
#---------------------------------------------------------------
# Fusion Microservice Kubernetes Utils
# Araf Karsh Hamid, (c) Copyright 2025
# License: Apache 2.0
# Version 0.01
#---------------------------------------------------------------

source ../../utils/colimaStatus

# uninstall NGINX ingress if found
uninstall_if_nginx_ingress_found
# uninstall Istio ingress if found
uninstall_if_istio_ingress_found

echo "---------------------------------------------------------------"
echo "Install the Fusion Water Services in Kubernetes GW cluster"
echo "---------------------------------------------------------------"
echo "Setup the Namespace / Gateway"
k8sgwFusionInstall
echo "2. Setup HTTP Route"
k8sgwApplyHttpRoute
cd ../app
allInstall
cd ../k8s-gw
echo "---------------------------------------------------------------"
echo "Sleeping for 7 seconds..."
sleep 7
echo "---------------------------------------------------------------"
list