#!/bin/bash
#---------------------------------------------------------------
# Fusion Microservice Kubernetes Utils
# Araf Karsh Hamid, (c) Copyright 2025
# License: Apache 2.0
# Version 0.01
#---------------------------------------------------------------

source ../../utils/colimaStatus

echo "---------------------------------------------------------------"
echo "UnInstall the Fusion Water Service in Kubernetes GW cluster"
echo "---------------------------------------------------------------"

# Check if the -s flag is passed
SILENT_MODE=false

# Loop through arguments
while getopts "s" opt; do
  case "$opt" in
    s) SILENT_MODE=true ;;
  esac
done

response="y"

# Perform the operation only if silent mode is NOT enabled
if [ "$SILENT_MODE" = false ]; then
  # Ask the user the question
  read -p "Do you want to uninstall Fusion-Water-Alpha K8s GW Service? (yes/y or no/n): " response
  # Normalize the input to lowercase for easy comparison
  response=$(echo "$response" | tr '[:upper:]' '[:lower:]')
fi

# Process the response
if [[ "$response" == "y" || "$response" == "yes" ]]; then
  echo "1. UnInstall the Kubernetes Http Routes"
  k8sgwDeleteHttpRoute
  cd ../app
  allUnInstall -s
  cd ../k8s-gw
  echo "---------------------------------------------------------------"
  echo "UnInstall the Namespace / Gateway "
fusionUnInstall -s
  echo "---------------------------------------------------------------"
  echo "Sleeping for 7 seconds..."
  sleep 7
  echo "---------------------------------------------------------------"
list
elif [[ "$response" == "n" || "$response" == "no" ]]; then
  echo "Alpha Service K8s GW Uninstallation canceled. Exiting."
else
  echo "Invalid input. Please enter yes/y or no/n."
fi

