#!/bin/bash
#---------------------------------------------------------------
# Fusion Microservice Kubernetes Utils
# Araf Karsh Hamid, (c) Copyright 2025
# License: Apache 2.0
# Version 0.01
#---------------------------------------------------------------

source ../../utils/colimaStatus

echo "---------------------------------------------------------------"
echo "Endpoints"
echo "---------------------------------------------------------------"
kubectl get ep -o wide -n fusion
echo "---------------------------------------------------------------"
echo "Please run 'allUpgradeCanary' before executity AB Testing....  "
echo "Shadow (Mirror data) the Fusion Water Services in Kubernetes GW cluster"
echo "---------------------------------------------------------------"
k8sgwApplyHttpRouteShadow
echo "---------------------------------------------------------------"
