#!/bin/bash
#---------------------------------------------------------------
# Fusion Microservice Kubernetes Utils
# Araf Karsh Hamid, (c) Copyright 2025
# License: Apache 2.0
# Version 0.01
#---------------------------------------------------------------

source ../../utils/colimaStatus

echo "---------------------------------------------------------------"
echo "Endpoints"
echo "---------------------------------------------------------------"
kubectl get ep -o wide -n fusion
echo "---------------------------------------------------------------"
echo "Canary: Upgrade the Fusion Services in Kubernetes GW cluster"
cd ../app
allUpgradeCanary
cd ../k8s-gw
echo "---------------------------------------------------------------"
echo "Endpoints"
echo "---------------------------------------------------------------"
kubectl get ep -o wide -n fusion
echo "---------------------------------------------------------------"
rolloutStatus
echo "---------------------------------------------------------------"
