#!/bin/bash
#---------------------------------------------------------------
# Fusion Kubernetes Utils
# Araf Karsh Hamid, (c) Copyright 2025
# License: Apache 2.0
# Version 0.01
#---------------------------------------------------------------

# Check if an argument is provided
if [ -z "$1" ]; then
  echo "---------------------------------------------------------------"
  echo "Usage: $0 <httproute-name>"
  echo "---------------------------------------------------------------"
  echo "Ingress : K8s Gateway / Http Route"
  echo "---------------------------------------------------------------"
  kubectl get gateway,httproute -o wide -n fusion
  exit 1
fi

kubectl describe httproute $1 -n fusion
