#!/bin/bash
#---------------------------------------------------------------
# Fusion Microservice Kubernetes Utils
# Araf Karsh Hamid, (c) Copyright 2025
# License: Apache 2.0
# Version 0.01
#---------------------------------------------------------------

source ../../utils/colimaStatus

echo "---------------------------------------------------------------"
echo "Enabling Traffic Splitting: Blue (Current) & Green (New versio)"
echo "---------------------------------------------------------------"
echo "kubectl apply -f ../../Yamls/k8s-gw/fusion-23-*-route-ab.yaml"
kubectl apply -f ../../Yamls/k8s-gw/fusion-23-k8s-product-route-ab.yaml
kubectl apply -f ../../Yamls/k8s-gw/fusion-23-k8s-cart-route-ab.yaml
kubectl apply -f ../../Yamls/k8s-gw/fusion-23-k8s-order-route-ab.yaml
echo "---------------------------------------------------------------"
kubectl get httproute -n fusion 
echo "---------------------------------------------------------------"
