#!/bin/bash
#---------------------------------------------------------------
# Fusion Microservice Kubernetes Utils
# Araf Karsh Hamid, (c) Copyright 2025
# License: Apache 2.0
# Version 0.01
#---------------------------------------------------------------

source ../../utils/colimaStatus

echo "---------------------------------------------------------------"
echo "Install the Fusion Service in Kubernetes/GW cluster"
echo "---------------------------------------------------------------"
echo "1. Deploy the Istio Namespace / Gateway in Kubernetes GW cluster"
kubectl create -f ../../Yamls/fusion-21-k8s-namespace.yaml
kubectl create -f ../../Yamls/fusion-22-k8s-gateway.yaml
echo "---------------------------------------------------------------"
