#!/bin/bash
#---------------------------------------------------------------
# Fusion Microservice Kubernetes Utils
# Araf Karsh Hamid, (c) Copyright 2025
# License: Apache 2.0
# Version 0.01
#---------------------------------------------------------------

source ../../utils/colimaStatus

echo "---------------------------------------------------------------"
echo "kubectl apply -f ../../Yamls/fusion-23-*-route.yaml"
kubectl apply -f ../../Yamls/fusion-23-k8s-alpha-route.yaml
kubectl apply -f ../../Yamls/fusion-23-k8s-product-route.yaml
kubectl apply -f ../../Yamls/fusion-23-k8s-cart-route.yaml
kubectl apply -f ../../Yamls/fusion-23-k8s-order-route.yaml
echo "---------------------------------------------------------------"
kubectl get httproute -n fusion 
echo "---------------------------------------------------------------"
