#!/bin/bash
#---------------------------------------------------------------
# Fusion Kubernetes Utils
# Araf Karsh Hamid, (c) Copyright 2025
# License: Apache 2.0
# Version 0.01
#---------------------------------------------------------------

echo "---------------------------------------------------------------"
echo "App Configuration and Secrets"
echo "---------------------------------------------------------------"
kubectl get configmaps -o wide -n fusion
echo "---------------------------------------------------------------"
kubectl get secrets -o wide -n fusion
echo "---------------------------------------------------------------"
echo "Pods / Deployments / Services / Endpoints"
echo "---------------------------------------------------------------"
kubectl get pods,deploy,svc,ep -o wide -n fusion
echo "---------------------------------------------------------------"
echo "Ingress : K8s Gateway / Http Route"
echo "---------------------------------------------------------------"
kubectl get gateway -o wide -n fusion
kubectl get httproute -o wide -n fusion
kubectl get svc -n nginx-gateway
echo "---------------------------------------------------------------"
kubectl get hpa -o wide -n fusion
echo "---------------------------------------------------------------"
